# Generated by Django 5.2.6 on 2025-09-09 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('brand', models.CharField(blank=True, max_length=35, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
