# Generated by Django 5.2.6 on 2025-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
